---
- hosts: all
  become: yes
  roles:
    - common

- hosts: etcd
  become: yes
  roles:
    - etcd

- hosts: patroni
  become: yes
  roles:
    - patroni

- hosts: haproxy
  become: yes
  roles:
    - haproxy