version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    privileged: true
    cgroup: host                               # <--- ТВОЯ НАХОДКА ИЗ STACKOVERFLOW
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - pgdata1:/var/lib/postgresql
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - patroni_net

  node2:
    build: .
    container_name: node2
    hostname: node2
    privileged: true
    cgroup: host                               # <--- ТВОЯ НАХОДКА ИЗ STACKOVERFLOW
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - pgdata2:/var/lib/postgresql
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - patroni_net

  node3:
    build: .
    container_name: node3
    hostname: node3
    privileged: true
    cgroup: host                               # <--- ТВОЯ НАХОДКА ИЗ STACKOVERFLOW
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - pgdata3:/var/lib/postgresql
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - patroni_net

  balancer:
    build: .
    container_name: balancer
    hostname: balancer
    privileged: true
    cgroup: host                               # <--- ТВОЯ НАХОДКА ИЗ STACKOVERFLOW
    ports:
      - "5000:5000"
      - "5001:5001"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - backup_data:/var/lib/pgbackrest
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - patroni_net

networks:
  patroni_net:
    driver: bridge

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  backup_data:
