---
# Плей для узлов баз данных
- name: Setup PostgreSQL HA Cluster
  hosts: etcd_nodes
  become: yes
  roles:
    - etcd             # 1. Поднимаем кворум
    - patroni          # 2. Поднимаем БД и связываем с кворумом
    - pgbackrest       # 3. Настраиваем отправку WAL логов

# Плей для сервера доступа и бекапов
- name: Setup Access Layer and Backup Repo
  hosts: balancers
  become: yes
  roles:
    - haproxy          # 1. L4 Роутинг (ищет Master-ноду через Patroni API)
    - pgbouncer        # 2. Пул соединений (слушает запросы и кидает их в HAProxy)
    - pgbackrest       # 3. Репозиторий хранения бекапов
