---
# Плей для кластера баз данных (БД)
- name: Setup PostgreSQL HA Cluster
  hosts: etcd_nodes
  become: yes
  roles:
    - etcd
    - patroni
    - pgbackrest       # Настраивает отправку WAL-логов на backup-сервер

# Плей для балансировщика и хранилища бекапов
- name: Setup Balancer and Backup Repo
  hosts: balancer
  become: yes
  roles:
    - balancer         # Настраивает HAProxy / PgBouncer
    - pgbackrest       # Настраивает локальный репозиторий для хранения архивов
