---
- name: Install etcd package
  apt:
    name: etcd
    state: present
    update_cache: yes

- name: Deploy etcd configuration
  template:
    src: etcd.j2
    dest: /etc/default/etcd
  notify: Restart etcd

- name: Start etcd service
  systemd:
    name: etcd
    state: started
    enabled: yes
