---
- name: Install PgBouncer package
  apt:
    name: pgbouncer
    state: present

- name: Deploy userlist.txt
  template:
    src: userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
    owner: postgres
    group: postgres
    mode: '0600'
  notify: Restart PgBouncer

- name: Deploy pgbouncer.ini configuration
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
  notify: Restart PgBouncer

- name: Allow PgBouncer startup in LSB script
  lineinfile:
    path: /etc/default/pgbouncer
    regexp: '^START='
    line: 'START=1'
    state: present

- name: Start PgBouncer service
  systemd:
    name: pgbouncer
    state: started
    enabled: yes
