---
- name: Install pgBackRest package
  apt:
    name: pgbackrest
    state: present

- name: Create directory for backup repository
  file:
    path: /var/lib/pgbackrest
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'
  when: inventory_hostname in groups['balancers']

- name: Deploy configuration for Repository
  template:
    src: pgbackrest-repo.conf.j2
    dest: /etc/pgbackrest.conf
  when: inventory_hostname in groups['balancers']

- name: Deploy configuration for Databases
  template:
    src: pgbackrest-client.conf.j2
    dest: /etc/pgbackrest.conf
  when: inventory_hostname in groups['etcd_nodes']
